=== lylee76/Webtechnology_labwork/Web_practical/Xml/1.dtd
<!ELEMENT book (title, author, isbn, publisher, edition, price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (fname, lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price currency CDATA #REQUIRED>

=== lylee76/Webtechnology_labwork/Web_practical/Xml/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="1.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<!DOCTYPE book SYSTEM "1.dtd">
<book>
    <title>Web Technology</title>
    <author>
        <fname>Basanta</fname>
        <lname>Chapagain</lname>
    </author>
    <isbn>56784323</isbn>
    <publisher>KEC</publisher>
    <edition>5th</edition>
    <price currency="npr">400</price>
</book>
