=== lylee76/Webtechnology_labwork/Web_practical/Xml/4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Define the authorType -->
  <xs:complexType name="authorType">
    <xs:sequence>
      <xs:element name="fname" type="xs:string"></xs:element>
      <xs:element name="mname" type="xs:string" minOccurs="0" maxOccurs="unbounded"></xs:element>
      <xs:element name="lname" type="xs:string"></xs:element>
    </xs:sequence>
    <xs:attribute name="title" type="xs:string"></xs:attribute>
  </xs:complexType>

  <!-- Define the priceType -->
  <xs:complexType name="priceType">
    <xs:simpleContent>
      <xs:extension base="xs:decimal">
        <xs:attribute name="currency" type="xs:string"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- Define the book element -->
  <xs:element name="book">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="author" type="authorType"></xs:element>
        <xs:element name="isbn" type="xs:int"></xs:element>
        <xs:element name="phone" type="xs:int"></xs:element>
        <xs:element name="email" type="xs:string"></xs:element>
        <xs:element name="price" type="priceType"></xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int" use="required"/>
    </xs:complexType>
  </xs:element>

  <!-- Define the books element -->
  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lylee76/Webtechnology_labwork/Web_practical/Xml/4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="4.xsd" type="application/xml" schematypens="http://www.w3.org/2001/XMLSchema"?>
<books   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="4.xsd">

    <book id="1">
        <title>Web Technology</title>
        <author title="mr.">
        <fname>Basanta</fname>
        <lname>Chapagain</lname>
        </author>
        <isbn>200</isbn>
        <phone>980000000</phone>
        <email>132@gmail.com</email>
        <price currency="Usd">600</price>
    </book>

    <book id="2">
        <author title="ms.">
        <fname>Amylee</fname>
        <mname>Pakhrin</mname>
        <lname>Tamang</lname>
        </author>
        <isbn>000</isbn>
        <phone>9810367014</phone>
        <email>abc1@gmail.com</email>
        <price currency="npr">355</price>
    </book>

    <book id="3">
        <title>OOP Java</title>
        <author title="mrs.">
        <fname>Kumari</fname>
        <lname>Ghalan</lname>
        </author>
        <isbn>666</isbn>
        <phone>0000000000</phone>
        <email>K123@gmail.com</email>
        <price currency="npr">400</price>
    </book>
</books>
