=== lylee76/Webtechnology_labwork/Web_practical/Xml/5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:complexType name="nameType">
    <xs:sequence>
      <xs:element name="fname" type="xs:string"></xs:element>
      <xs:element name="mname" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
      <xs:element name="lname" type="xs:string"></xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="addressType">
    <xs:sequence>
      <xs:element name="permanent" type="xs:string"></xs:element>
      <xs:element name="temporary" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
    </xs:sequence>
    <xs:attribute name="address" type="xs:string"></xs:attribute>
  </xs:complexType>


    <xs:simpleType name="phone">
      <xs:restriction base="xs:int">
        <xs:pattern value="^(98|97)\d{8}$"></xs:pattern>
      </xs:restriction>
    </xs:simpleType>



    <xs:simpleType name="email">
      <xs:restriction base="xs:string">
        <xs:pattern value="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"></xs:pattern>
      </xs:restriction>
    </xs:simpleType>


  <xs:element name="dob" type="xs:date"></xs:element>

  <xs:element name="student">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"></xs:element>
        <xs:element name="phone" type="xs:int"></xs:element>
        <xs:element name="address" type="xs:string"></xs:element>
        <xs:element name="email" type="xs:string"></xs:element>
        <xs:element name="dob" type="xs:date"></xs:element>
      </xs:sequence>
      <xs:attribute name="id" type="xs:int"></xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="student" type="xs:anyType" minOccurs="0" maxOccurs="unbounded"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== lylee76/Webtechnology_labwork/Web_practical/Xml/5.xml
<?xml version="1.0" encoding="UTF-8"?>
<students xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="5.xsd">
    <student id="1">
        <name>
            <fname>Anu</fname>
            <lname>Kumri</lname>
        </name>
        <email>anu321@gmail.com</email>
        <phone>981803578</phone>
        <address>
            <permanent address="Jhapa"></permanent>
            <temporary address="Kathmandu"></temporary>
        </address>
        <dob>2004-05-04</dob>
    </student>
    <student id="2">
        <name>
            <fname>Amylee</fname>
            <mname>Pakhrin</mname>
            <lname>Tamang</lname>
        </name>
        <email>amylee123@gmail.com</email>
        <phone>9834125687</phone>
        <address>
            <permanent address="Sarlahi"></permanent>
            <temporary address="Kathmandu"></temporary>
        </address>
        <dob>2003-09-22</dob>
    </student>
</students>
